# Generated by Django 3.1.2 on 2022-01-30 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', 'nnn0001_auto_20220129_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='notas',
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(default='dieccion', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default='4433000000', help_text='Ingresa el teléfono a 10 dígitos', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10,15}$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(regex='^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\\-]*[a-zA-Z0-9])\\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\\-]*[A-Za-z0-9])$')]),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='descripcion', help_text='Aquí puedes detallar las características del descuento o beneficio', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='Ingresa la categoria(p. ej. Salud, Universidades)', max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ProductoInstance',
        ),
    ]
