# Generated by Django 3.1.2 on 2022-01-29 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', 'nnn0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa el beneficio (p. ej. 10%)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa la categoria(p. ej. Salud, Universidades)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular Producto across whole library', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=200)),
                ('due_back', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Producto availability', max_length=1)),
            ],
            options={
                'ordering': ['due_back'],
                'permissions': (('can_mark_returned', 'Set Producto as returned'),),
            },
        ),
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre', 'descripcion']},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre', 'empresa']},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='name',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='Empresa',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imprint',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='title',
        ),
        migrations.AddField(
            model_name='empresa',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, verbose_name='died'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(default='d', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='n', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='isbn',
            field=models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas',
            field=models.TextField(help_text='Ingresa notas acerca del categoria', max_length=1000),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='productoinstance',
            name='Producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo.producto'),
        ),
        migrations.AddField(
            model_name='productoinstance',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='beneficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.beneficio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(help_text='Escoge un categoria de este servicio o producto', to='catalogo.Categoria'),
        ),
    ]
